import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

const SEED_DESCRIPTIONS = [
  // GBP
  'Client payment - Acme Corp',
  'Consulting service fee',
  'Office rent - January',
  'Office rent - February',
  'Office rent - March',
  'Staff salaries',
  'AWS cloud services',
  'Google Ads campaign',
  'Office supplies',
  'HMRC VAT payment',
  'Client payment - Beta Ltd',
  'Support contract renewal',
  'GitHub Enterprise',
  'LinkedIn Ads',
  'Business insurance',
  'Client payment - Gamma PLC',
  'Freelance project delivery',
  'Supplier materials',
  'Datadog monitoring',
  'Trade show sponsorship',
  'Bank loan repayment',
  // ILS
  'Main client - monthly payment',
  'Consulting service - Project A',
  'Office rent - January',
  'Staff salaries - January',
  'Supplier materials - Order #101',
  'Digital advertising campaign',
  'Income tax advance payment',
  'Cloud storage - AWS',
  'Special project - Client B',
  'Office rent - February',
  'Staff salaries - February',
  'Business insurance',
  'Office supplies',
  'Software & licenses',
  'Consulting service - Project C',
  'Additional income - new client',
  'Office rent - March',
  'Staff salaries - March',
  'Supplier materials - Order #115',
  'Facebook & Instagram - advertising',
  'Business loan - monthly repayment',
  // USD
  'Client payment - US Corp',
  'SaaS subscription revenue',
  'Staff salary - US team',
  'AWS US region',
  'Google Ads US',
  'Stripe payment processing fees',
  'IRS estimated tax payment',
  'Client payment - TechStart Inc',
  'Annual license renewal',
  'Cloudflare & Vercel',
  'HubSpot CRM',
  'Legal & compliance fees',
  'Client payment - Global Ventures',
  'API usage fees income',
  'Hardware & equipment',
  'AWS + GCP services',
  'Conference & events',
  'Bank loan payment',
];

export async function POST() {
  const { count } = await prisma.transaction.deleteMany({
    where: { description: { in: SEED_DESCRIPTIONS } },
  });
  return NextResponse.json({ deleted: count });
}
